# Generated by Django 4.2.30 on 2026-04-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='title',
        ),
    ]
